In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import quandl
import time
%matplotlib inline

In [9]:
df = quandl.get("NSE/NIFTY_50", start_date='2007-01-01')

In [10]:
df.head()

,Open,High,Low,Close,Shares Traded,Turnover (Rs. Cr)
Date,,,,,,
2007-01-02,3966.25,4016.65,3964.95,4007.40,40789960.0,1929.76
2007-01-03,4007.70,4029.80,3985.00,4024.05,63826475.0,3291.66
2007-01-04,4027.30,4041.00,3979.80,3988.80,67096186.0,3446.19
2007-01-05,3990.15,4011.45,3969.65,3983.40,69146575.0,3558.69
2007-01-08,3983.30,3987.45,3913.00,3933.40,63615668.0,3590.08

In [11]:
def HA(df):
    df['HA_Close']=(df['Open']+ df['High']+ df['Low']+df['Close'])/4

    idx = df.index.name
    df.reset_index(inplace=True)

    for i in range(0, len(df)):
        if i == 0:
            df.set_value(i, 'HA_Open', ((df.get_value(i, 'Open') + df.get_value(i, 'Close')) / 2))
        else:
            df.set_value(i, 'HA_Open', ((df.get_value(i - 1, 'HA_Open') + df.get_value(i - 1, 'HA_Close')) / 2))

    if idx:
        df.set_index(idx, inplace=True)

    df['HA_High']=df[['HA_Open','HA_Close','High']].max(axis=1)
    df['HA_Low']=df[['HA_Open','HA_Close','Low']].min(axis=1)
    return df

In [12]:
def test_HA():
    print('HA Test')
    start = time.time()
    HA(df)
    end = time.time()
    print('Time taken by set and get value functions for HA {}'.format(end-start))

    start = time.time()
    df['HA_Close_t']=(df['Open']+ df['High']+ df['Low']+df['Close'])/4

    from collections import namedtuple
    nt = namedtuple('nt', ['Open','Close'])
    previous_row = nt(df.ix[0,'Open'],df.ix[0,'Close'])
    i = 0
    for row in df.itertuples():
        ha_open = (previous_row.Open + previous_row.Close) / 2
        df.ix[i,'HA_Open_t'] = ha_open
        previous_row = nt(ha_open, row.Close)
        i += 1

    df['HA_High_t']=df[['HA_Open_t','HA_Close_t','High']].max(axis=1)
    df['HA_Low_t']=df[['HA_Open_t','HA_Close_t','Low']].min(axis=1)
    end = time.time()
    print('Time taken by ix (iloc, loc) functions for HA {}'.format(end-start))

In [13]:
test_HA()

HA Test
Time taken by set and get value functions for HA 0.10535192489624023

/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # This is added back by InteractiveShellApp.init_path()
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # This is added back by InteractiveShellApp.init_path()
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:13: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  del sys.path[0]
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:17: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

Time taken by ix (iloc, loc) functions for HA 0.8039050102233887

In [14]:
HA(df)

/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # This is added back by InteractiveShellApp.init_path()
/Users/mayank.gupta/venv/DLaaS/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # This is added back by InteractiveShellApp.init_path()

,Open,High,Low,Close,Shares Traded,Turnover (Rs. Cr),HA_Close,HA_Open,HA_High,HA_Low,HA_Close_t,HA_Open_t,HA_High_t,HA_Low_t
Date,,,,,,,,,,,,,,
2007-01-02,3966.25,4016.65,3964.95,4007.40,40789960.0,1929.76,3988.8125,3986.825000,4016.650000,3964.950000,3988.8125,3986.825000,4016.650000,3964.950000
2007-01-03,4007.70,4029.80,3985.00,4024.05,63826475.0,3291.66,4011.6375,3987.818750,4029.800000,3985.000000,4011.6375,3997.112500,4029.800000,3985.000000
2007-01-04,4027.30,4041.00,3979.80,3988.80,67096186.0,3446.19,4009.2250,3999.728125,4041.000000,3979.800000,4009.2250,4010.581250,4041.000000,3979.800000
2007-01-05,3990.15,4011.45,3969.65,3983.40,69146575.0,3558.69,3988.6625,4004.476562,4011.450000,3969.650000,3988.6625,3999.690625,4011.450000,3969.650000
2007-01-08,3983.30,3987.45,3913.00,3933.40,63615668.0,3590.08,3954.2875,3996.569531,3996.569531,3913.000000,3954.2875,3991.545313,3991.545313,3913.000000
2007-01-09,3933.30,3963.75,3890.75,3911.40,65321592.0,3753.18,3924.8000,3975.428516,3975.428516,3890.750000,3924.8000,3962.472656,3963.750000,3890.750000
2007-01-10,3910.95,3911.95,3841.70,3850.30,68470689.0,3892.68,3878.7250,3950.114258,3950.114258,3841.700000,3878.7250,3936.936328,3936.936328,3841.700000
2007-01-11,3852.15,3953.10,3833.60,3942.25,83152375.0,5058.74,3895.2750,3914.419629,3953.100000,3833.600000,3895.2750,3893.618164,3953.100000,3833.600000
2007-01-12,3944.55,4059.15,3944.55,4052.45,81362992.0,4727.43,4000.1750,3904.847314,4059.150000,3904.847314,4000.1750,3917.934082,4059.150000,3917.934082
2007-01-15,4052.85,4099.65,4052.40,4078.40,81723925.0,4103.23,4070.8250,3952.511157,4099.650000,3952.511157,4070.8250,3985.192041,4099.650000,3985.192041
2007-01-16,4090.70,4107.45,4067.90,4080.50,60251260.0,3626.60,4086.6375,4011.668079,4107.450000,4011.668079,4086.6375,4031.796021,4107.450000,4031.796021
2007-01-17,4084.90,4096.75,4071.55,4076.45,59073863.0,3077.88,4082.4125,4049.152789,4096.750000,4049.152789,4082.4125,4056.148010,4096.750000,4056.148010
2007-01-18,4075.20,4140.25,4075.20,4109.05,75646344.0,4020.61,4099.9250,4065.782645,4140.250000,4065.782645,4099.9250,4066.299005,4140.250000,4066.299005
2007-01-19,4126.00,4137.15,4058.35,4090.15,85555366.0,4541.53,4102.9125,4082.853822,4137.150000,4058.350000,4102.9125,4087.674503,4137.150000,4058.350000
2007-01-22,4089.60,4114.50,4069.95,4102.45,63758853.0,3514.19,4094.1250,4092.883161,4114.500000,4069.950000,4094.1250,4088.912251,4114.500000,4069.950000
2007-01-23,4102.65,4105.10,4056.45,4066.10,80442797.0,3783.57,4082.5750,4093.504081,4105.100000,4056.450000,4082.5750,4095.681126,4105.100000,4056.450000
2007-01-24,4066.60,4098.25,4065.75,4089.90,90298316.0,3760.90,4080.1250,4088.039540,4098.250000,4065.750000,4080.1250,4080.890563,4098.250000,4065.750000
2007-01-25,4092.05,4157.95,4090.10,4147.70,130890355.0,5541.44,4121.9500,4084.082270,4157.950000,4084.082270,4121.9500,4085.395281,4157.950000,4085.395281
2007-01-29,4148.40,4167.15,4115.75,4124.45,94946217.0,3998.53,4138.9375,4103.016135,4167.150000,4103.016135,4138.9375,4116.547641,4167.150000,4115.750000
2007-01-31,4123.85,4137.85,4068.55,4082.70,114992600.0,5378.20,4103.2375,4120.976818,4137.850000,4068.550000,4103.2375,4120.498820,4137.850000,4068.550000
2007-02-01,4083.40,4141.60,4081.10,4137.20,73460198.0,3409.67,4110.8250,4112.107159,4141.600000,4081.100000,4110.8250,4101.599410,4141.600000,4081.100000
2007-02-02,4140.20,4198.70,4132.95,4183.50,92547027.0,4676.12,4163.8375,4111.466079,4198.700000,4111.466079,4163.8375,4119.399705,4198.700000,4119.399705
2007-02-05,4193.15,4219.00,4170.00,4215.35,62178023.0,3381.35,4199.3750,4137.651790,4219.000000,4137.651790,4199.3750,4151.449853,4219.000000,4151.449853
2007-02-06,4216.55,4228.15,4186.15,4195.90,64125214.0,3421.59,4206.6875,4168.513395,4228.150000,4168.513395,4206.6875,4183.399926,4228.150000,4183.399926
2007-02-07,4198.20,4232.30,4192.85,4224.25,66702277.0,3804.96,4211.9000,4187.600447,4232.300000,4187.600447,4211.9000,4189.649963,4232.300000,4189.649963
2007-02-08,4232.00,4245.30,4188.45,4223.40,69459583.0,3340.66,4222.2875,4199.750224,4245.300000,4188.450000,4222.2875,4206.949982,4245.300000,4188.450000
2007-02-09,4223.50,4239.20,4171.80,4187.40,66107054.0,3610.60,4205.4750,4211.018862,4239.200000,4171.800000,4205.4750,4215.174991,4239.200000,4171.800000
2007-02-12,4187.20,4187.20,4044.35,4058.30,91427563.0,3947.24,4119.2625,4208.246931,4208.246931,4044.350000,4119.2625,4201.287495,4201.287495,4044.350000
2007-02-13,4069.10,4132.70,3998.30,4044.55,97888267.0,4496.49,4061.1625,4163.754715,4163.754715,3998.300000,4061.1625,4129.793748,4132.700000,3998.300000
2007-02-14,4044.90,4057.35,3965.20,4047.10,82077938.0,4215.28,4028.6375,4112.458608,4112.458608,3965.200000,4028.6375,4087.171874,4087.171874,3965.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-22,10612.65,10646.25,10512.00,10526.75,246926671.0,12254.36,10574.4125,10657.144457,10657.144457,10512.000000,10574.4125,10639.070755,10646.250000,10512.000000
2018-11-26,10568.30,10637.80,10489.75,10628.60,332863041.0,15927.25,10581.1125,10615.778478,10637.800000,10489.750000,10581.1125,10582.910377,10637.800000,10489.750000
2018-11-27,10621.45,10695.15,10596.35,10685.60,382834178.0,17296.28,10649.6375,10598.445489,10695.150000,10596.350000,10649.6375,10605.755189,10695.150000,10596.350000
2018-11-28,10708.75,10757.80,10699.85,10728.85,437627174.0,17737.28,10723.8125,10624.041495,10757.800000,10624.041495,10723.8125,10645.677594,10757.800000,10645.677594
2018-11-29,10808.70,10883.05,10782.35,10858.70,712650890.0,26283.43,10833.2000,10673.926997,10883.050000,10673.926997,10833.2000,10687.263797,10883.050000,10687.263797
2018-11-30,10892.10,10922.45,10835.10,10876.75,467857329.0,19964.33,10881.6000,10753.563499,10922.450000,10753.563499,10881.6000,10772.981899,10922.450000,10772.981899
2018-12-03,10930.70,10941.20,10845.35,10883.75,422358631.0,18484.91,10900.2500,10817.581749,10941.200000,10817.581749,10900.2500,10824.865949,10941.200000,10824.865949
2018-12-04,10877.10,10890.95,10833.35,10869.50,332137359.0,15857.16,10867.7250,10858.915875,10890.950000,10833.350000,10867.7250,10854.307975,10890.950000,10833.350000
2018-12-05,10820.45,10821.05,10747.95,10782.90,322019985.0,15176.26,10793.0875,10863.320437,10863.320437,10747.950000,10793.0875,10861.903987,10861.903987,10747.950000
2018-12-06,10718.15,10722.65,10588.25,10601.15,328275196.0,16488.87,10657.5500,10828.203969,10828.203969,10588.250000,10657.5500,10822.401994,10822.401994,10588.250000
2018-12-07,10644.80,10704.55,10599.35,10693.70,335849636.0,18597.83,10660.6000,10742.876984,10742.876984,10599.350000,10660.6000,10711.775997,10711.775997,10599.350000
2018-12-10,10508.70,10558.85,10474.95,10488.45,393097292.0,16524.36,10507.7375,10701.738492,10701.738492,10474.950000,10507.7375,10702.737998,10702.737998,10474.950000
2018-12-11,10350.05,10567.15,10333.85,10549.15,438699334.0,20112.91,10450.0500,10604.737996,10604.737996,10333.850000,10450.0500,10595.593999,10595.593999,10333.850000
2018-12-12,10591.00,10752.20,10560.80,10737.60,371697496.0,17447.45,10660.4000,10527.393998,10752.200000,10527.393998,10660.4000,10572.372000,10752.200000,10560.800000
2018-12-13,10810.75,10838.60,10749.50,10791.55,387810061.0,17582.80,10797.6000,10593.896999,10838.600000,10593.896999,10797.6000,10654.986000,10838.600000,10654.986000
2018-12-14,10784.50,10815.75,10752.10,10805.45,350579275.0,14486.10,10789.4500,10695.748500,10815.750000,10695.748500,10789.4500,10723.268000,10815.750000,10723.268000
2018-12-17,10853.20,10900.35,10844.85,10888.35,306145514.0,12528.59,10871.6875,10742.599250,10900.350000,10742.599250,10871.6875,10764.359000,10900.350000,10764.359000
2018-12-18,10850.90,10915.40,10819.10,10908.70,294942271.0,13556.45,10873.5250,10807.143375,10915.400000,10807.143375,10873.5250,10826.354500,10915.400000,10819.100000
2018-12-19,10930.55,10985.15,10928.00,10967.30,321801803.0,17172.64,10952.7500,10840.334187,10985.150000,10840.334187,10952.7500,10867.527250,10985.150000,10867.527250
2018-12-20,10885.20,10962.55,10880.05,10951.70,328802751.0,14945.94,10919.8750,10896.542094,10962.550000,10880.050000,10919.8750,10917.413625,10962.550000,10880.050000
2018-12-21,10944.25,10963.65,10738.65,10754.00,389235107.0,18663.85,10850.1375,10908.208547,10963.650000,10738.650000,10850.1375,10934.556812,10963.650000,10738.650000
2018-12-24,10780.90,10782.30,10649.25,10663.50,230291344.0,10695.60,10718.9875,10879.173023,10879.173023,10649.250000,10718.9875,10844.278406,10844.278406,10649.250000
2018-12-26,10635.45,10747.50,10534.55,10729.85,271942701.0,12831.99,10661.8375,10799.080262,10799.080262,10534.550000,10661.8375,10753.889203,10753.889203,10534.550000
2018-12-27,10817.90,10834.20,10764.45,10779.80,470160392.0,19119.88,10799.0875,10730.458881,10834.200000,10730.458881,10799.0875,10741.869602,10834.200000,10741.869602
2018-12-28,10820.95,10893.60,10817.15,10859.90,253086507.0,12615.01,10847.9000,10764.773190,10893.600000,10764.773190,10847.9000,10760.834801,10893.600000,10760.834801
2018-12-31,10913.20,10923.55,10853.20,10862.55,186494657.0,10176.13,10888.1250,10806.336595,10923.550000,10806.336595,10888.1250,10810.367400,10923.550000,10810.367400
2019-01-01,10881.70,10923.60,10807.10,10910.10,159404542.0,8688.26,10880.6250,10847.230798,10923.600000,10807.100000,10880.6250,10836.458700,10923.600000,10807.100000
2019-01-02,10868.85,10895.35,10735.05,10792.50,309665939.0,15352.25,10822.9375,10863.927899,10895.350000,10735.050000,10822.9375,10873.279350,10895.350000,10735.050000
2019-01-03,10796.80,10814.05,10661.25,10672.25,286241745.0,15030.45,10736.0875,10843.432699,10843.432699,10661.250000,10736.0875,10832.889675,10832.889675,10661.250000
2019-01-04,10699.70,10741.05,10628.65,10727.35,296596655.0,14516.74,10699.1875,10789.760100,10789.760100,10628.650000,10699.1875,10752.569838,10752.569838,10628.650000